// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuoNDS.Models;
using YMTWEB.Data;

#nullable disable

namespace YMTWEB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YMTWEB.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            // กำหนดว่า MasterStyle เป็น Keyless Entity
          

            //modelBuilder.Entity("YMTWEB.Models.YMTGUser", b =>
            //    {
            //        b.Property<int>("Id")
            //            .ValueGeneratedOnAdd()
            //            .HasColumnType("int");

            //        SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            //        b.Property<string>("Dept")
            //            .HasColumnType("nvarchar(max)");

            //        b.Property<string>("Email")
            //            .HasColumnType("nvarchar(max)");

            //        b.Property<string>("EmployeeId")
            //            .HasColumnType("nvarchar(max)");

            //        b.Property<string>("Factory")
            //            .HasColumnType("nvarchar(max)");

            //        b.Property<string>("GNXPODepartment")
            //            .HasColumnType("nvarchar(max)");

            //        b.Property<bool>("Resign")
            //            .HasColumnType("bit");

            //        b.Property<string>("Status")
            //            .HasColumnType("nvarchar(max)");

            //        b.Property<string>("UserGroup")
            //            .HasColumnType("nvarchar(max)");

            //        b.Property<int>("YPTLevel")
            //            .HasColumnType("int");

            //        b.Property<string>("YPTName")
            //            .HasColumnType("nvarchar(max)");

            //        b.Property<string>("YPTPODepartment")
            //            .HasColumnType("nvarchar(max)");

            //        b.Property<string>("YPTPass")
            //            .HasColumnType("nvarchar(max)");

            //        b.Property<string>("YPTUser")
            //            .HasColumnType("nvarchar(max)");

            //        b.HasKey("Id");

            //        b.ToTable("YMTG_USER");
            //    });
#pragma warning restore 612, 618
        }
    }
}
